services:
  wormgas:
    image: ghcr.io/williamjacksn/wormgas
    init: true

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/wormgas
    init: true
    volumes:
      - ./:/home/python/wormgas
    working_dir: /home/python/wormgas
